{% set version = "0.7.10" %}

package:
  name: aws-c-http
  version: {{ version }}

source:
  url: https://github.com/awslabs/aws-c-http/archive/v{{ version }}.tar.gz
  sha256: 2dc02b241b477c35845e8f19d8f40647d8e1cae9f884b186f0051a58dd980193

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-http", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-cal
    - aws-c-common
    - aws-c-compression
    - aws-c-io

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-http${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/http/http.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\http\\http.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-http.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-http
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the HTTP/1.1 and HTTP/2 specifications

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
