{% set name = "aws-c-http" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a3afad3501155f7c1e46274a004db3637a5fca451f15df8ad0d936ea0f7d6bce

build:
  number: 3
  run_exports:
    - {{ pin_subpackage("aws-c-http", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-common
    - aws-c-compression
    - aws-c-io

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-http${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/http/http.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\http\\http.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-http.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-http
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the HTTP/1.1 and HTTP/2 specifications

extra:
  recipe-maintainers:
    - xhochy
